name: Rapport de bug
about: Signaler un problème avec les cartes Pronote
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug !

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Décris clairement le problème rencontré
      placeholder: |
        Quand j'essaye de..., le résultat est... au lieu de...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Étapes de reproduction
      description: Comment reproduire le bug ?
      placeholder: |
        1. Aller sur...
        2. Cliquer sur...
        3. Voir l'erreur...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer normalement ?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Quelle version de lovelace-pronote utilises-tu ?
      placeholder: ex. 1.0.1
    validations:
      required: true

  - type: input
    id: ha_version
    attributes:
      label: Version Home Assistant
      description: Quelle version de Home Assistant utilises-tu ?
      placeholder: ex. 2024.2.0
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Navigateur
      description: Quel navigateur utilises-tu ?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Autre
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Copie-colle les erreurs de la console du navigateur (F12)
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration YAML
      description: Ta configuration de carte (si applicable)
      render: yaml

  - type: checkboxes
    id: terms
    attributes:
      label: Vérifications
      options:
        - label: J'ai cherché dans les issues existantes
          required: true
        - label: J'utilise la dernière version disponible
          required: true
